[Feat] [SCRUM-83] 마이 프로필 수정 페이지 UI 구현 #50
Last-transcendence/ft_transcendence pull request #64
Opened 2023-12-27 10:57 UTC by flatroad

## 📌 개요 
 - 마이 프로필 수정 페이지 UI 구현
## 💻 작업사항 
 - 프로필 수정 페이지 UI 구현

2023-12-27 15:10 UTC, hyeon81 requested changes

2023-12-27 15:10 UTC, hyeon81 commented on src/service/nextjs/src/component/profile/modifyProfile/index.tsx
> +			} else {
이 부분은 작동하지 않습니다
https://axios-http.com/kr/docs/handling_errors
이 부분을 참고해보면, 2xx 이외의 응답은 axios에서 기본적으로 error로 처리하기 때문에, 2xx 이외의 응답은 catch문에 들어가게 됩니다.

2023-12-28 10:11 UTC, flatroad commented on src/service/nextjs/src/component/profile/modifyProfile/index.tsx
> +				}, 1000);
의도는 에러발생시 리로드를 해줄려고 했던 거였지만 현지님과 이야기 통해 필요하지 않다는 것을 알았습니다. 해당 페이지 전체 수정이 불가피하여(초기안과 다른 페이지) 추후 참고하여 수정하겠습니다.

2023-12-28 10:11 UTC, flatroad commented on src/service/nextjs/src/component/profile/modifyProfile/index.tsx
> +			} else {
넵. status를 통해서 에러 정보 확인할 수 있다는 것 알았습니다. 감사합니다.

2023-12-28 10:14 UTC, hyeon81 approved these changes

2023-12-28 10:15 UTC, merged